// src/screens/styles/project-detail.styles.ts
import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';
import { shadowPresets } from '../../theme/shadows';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    backgroundColor: colors.backgroundLight,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    ...shadowPresets.header,
  },
  headerTitle: {
    flex: 1,
    fontSize: typography.sizes.lg,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
    marginHorizontal: spacing.xs,
  },
  headerActions: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  iconBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  headerIcon: {
    fontSize: typography.sizes.lg,
  },
  activeFilterIcon: {
    opacity: 0.7,
  },
  filterBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: colors.error,
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBadgeText: {
    color: colors.white,
    fontSize: typography.sizes.xs,
    fontWeight: '700',
    paddingHorizontal: spacing.xs,
  },
  searchContainer: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.backgroundLight,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.backgroundLight,
    borderRadius: 12,
    paddingHorizontal: spacing.sm,
    height: 44,
  },
  searchIcon: {
    fontSize: typography.sizes.md,
    marginRight: spacing.xs,
    color: colors.textSecondary,
  },
  searchInput: {
    flex: 1,
    fontSize: typography.sizes.md,
    color: colors.textPrimary,
    padding: 0,
  },
  clearIcon: {
    fontSize: typography.sizes.md,
    color: colors.textSecondary,
    padding: spacing.xs,
  },
  statsScroll: {
    backgroundColor: colors.backgroundLight,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  statsContainer: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
    alignItems: 'flex-start',
  },
  statCard: {
    backgroundColor: colors.backgroundLight,
    borderRadius: 12,
    padding: spacing.sm,
    minWidth: 100,
    maxHeight: 96,
    minHeight: 72,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statIcon: {
    fontSize: 20,
    marginBottom: spacing.xs,
  },
  statPending: {
    backgroundColor: colors.warningLight,
    borderColor: colors.warning,
  },
  statApproved: {
    backgroundColor: colors.successLight,
    borderColor: colors.success,
  },
  statRejected: {
    backgroundColor: colors.errorLight,
    borderColor: colors.error,
  },
  statLabel: {
    fontSize: typography.sizes.sm,
    color: colors.textSecondary,
    fontWeight: '600',
    marginBottom: 2,
  },
  statValue: {
    fontSize: typography.sizes.lg,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  chipScroll: {
    backgroundColor: colors.backgroundLight,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  chipSection: {
    backgroundColor: colors.backgroundLight,
    borderBottomWidth: 1,
    borderColor: colors.border,
    paddingTop: spacing.xs,
  },
  chipSectionTitle: {
    fontSize: typography.sizes.sm,
    fontWeight: '600',
    color: colors.textPrimary,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  chipContainer: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DBEAFE',
    borderRadius: 20,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    gap: spacing.xs,
  },
  chipText: {
    fontSize: typography.sizes.sm,
    color: '#1E40AF',
    fontWeight: '500',
  },
  chipRemove: {
    fontSize: 18,
    color: '#1E40AF',
    fontWeight: '700',
    minWidth: 24,
    minHeight: 24,
    textAlign: 'center',
    lineHeight: 22,
  },
  clearAllText: {
    fontSize: typography.sizes.sm,
    color: colors.error,
    fontWeight: '600',
    paddingVertical: spacing.xs,
  },
  filtersPanel: {
    backgroundColor: colors.backgroundLight,
    borderBottomWidth: 1,
    borderColor: colors.border,
    maxHeight: 400,
  },
  filterPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.backgroundLight,
  },
  filterPanelTitle: {
    fontSize: typography.sizes.md,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  filterPanelClose: {
    fontSize: typography.sizes.lg,
    color: colors.textSecondary,
    fontWeight: '600',
    padding: spacing.xs,
  },
  filterScrollContent: {
    paddingBottom: spacing.sm,
  },
  filterPanelFooter: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  filterSectionTitle: {
    fontSize: typography.sizes.md,
    fontWeight: '600',
    color: colors.textPrimary,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  filterOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  filterChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 16,
    backgroundColor: colors.backgroundLight,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipText: {
    fontSize: typography.sizes.sm,
    color: colors.textSecondary,
  },
  filterChipTextSelected: {
    color: colors.white,
    fontWeight: '500',
  },
  editLink: {
    fontSize: typography.sizes.sm,
    color: colors.primary,
    fontWeight: '600',
  },
  selectedCategory: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primaryLight,
    borderRadius: 16,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    gap: spacing.xs,
  },
  selectedCategoryText: {
    fontSize: typography.sizes.sm,
    color: colors.primary,
    fontWeight: '500',
  },
  removeIcon: {
    fontSize: typography.sizes.sm,
    color: colors.primary,
    fontWeight: '600',
  },
  placeholderText: {
    fontSize: typography.sizes.sm,
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  amountRange: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  amountInput: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.sm,
    paddingHorizontal: spacing.sm,
    fontSize: typography.sizes.sm,
    backgroundColor: colors.backgroundLight,
  },
  amountSeparator: {
    fontSize: typography.sizes.md,
    color: colors.textSecondary,
  },
  sortSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 44,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.sm,
    paddingHorizontal: spacing.sm,
    backgroundColor: colors.backgroundLight,
  },
  sortSelectorText: {
    fontSize: typography.sizes.sm,
    color: colors.textPrimary,
  },
  chevron: {
    fontSize: typography.sizes.md,
    color: colors.textSecondary,
  },
  applyButton: {
    backgroundColor: colors.primary,
    borderRadius: spacing.md,
    padding: spacing.md,
    alignItems: 'center',
    marginTop: spacing.md,
    marginBottom: spacing.xs,
  },
  applyButtonText: {
    color: colors.white,
    fontSize: typography.sizes.md,
    fontWeight: '600',
  },
  listContainer: {
    padding: spacing.md,
  },
  listHeader: {
    marginBottom: spacing.sm,
  },
  resultCount: {
    fontSize: typography.sizes.sm,
    color: colors.textSecondary,
  },
  expenseItem: {
    flexDirection: 'row',
    gap: spacing.md,
    backgroundColor: colors.white,
    marginBottom: spacing.xs,
    padding: spacing.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadowPresets.listItem,
  },
  expenseIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  expenseIconText: {
    fontSize: 24,
  },
  expenseTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  expenseTitle: {
    fontSize: typography.sizes.md,
    fontWeight: '600',
    color: colors.textPrimary,
    flex: 1,
    marginRight: spacing.xs,
  },
  expenseAmount: {
    fontSize: typography.sizes.md,
    fontWeight: '700',
    color: colors.primary,
  },
  expenseBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  expenseMeta: {
    fontSize: typography.sizes.sm,
    color: colors.textSecondary,
    flex: 1,
    maxWidth: '60%',
  },
  statusPill: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 12,
    marginLeft: spacing.xs,
  },
  statusPillText: {
    fontSize: typography.sizes.xs,
    fontWeight: '700',
  },
  statusPending: {
    backgroundColor: colors.warningLight,
  },
  statusApproved: {
    backgroundColor: colors.successLight,
  },
  statusRejected: {
    backgroundColor: colors.errorLight,
  },
  gridItem: {
    flex: 1,
    margin: 4,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    aspectRatio: 1,
    alignItems: 'center',
  },
  gridIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  gridIconText: {
    fontSize: 20,
  },
  gridCategory: {
    fontSize: typography.sizes.sm,
    fontWeight: '500',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  gridAmount: {
    fontSize: typography.sizes.md,
    fontWeight: '700',
    color: colors.primary,
  },
  gridStatus: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridStatusText: {
    fontSize: typography.sizes.xs,
    fontWeight: '700',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  emptyStateEmoji: {
    fontSize: 48,
    marginBottom: spacing.md,
  },
  emptyStateTitle: {
    fontSize: typography.sizes.lg,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  emptyStateText: {
    fontSize: typography.sizes.md,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  fab: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.md,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadowPresets.fab,
  },
  fabIcon: {
    color: colors.white,
    fontSize: 24,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: {
    fontSize: typography.sizes.lg,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  modalClose: {
    fontSize: typography.sizes.xl,
    color: colors.textSecondary,
    padding: spacing.xs,
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderColor: colors.backgroundLight,
  },
  modalOptionSelected: {
    backgroundColor: colors.primaryLight,
  },
  modalOptionText: {
    fontSize: typography.sizes.md,
    color: colors.textPrimary,
  },
  modalOptionTextSelected: {
    color: colors.primary,
    fontWeight: '600',
  },
  checkmark: {
    fontSize: typography.sizes.md,
    color: colors.primary,
    fontWeight: '700',
  },
  modalApplyButton: {
    backgroundColor: colors.primary,
    padding: spacing.md,
    alignItems: 'center',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  modalApplyText: {
    color: colors.white,
    fontSize: typography.sizes.md,
    fontWeight: '600',
  },
  datePickerContainer: {
    padding: spacing.md,
  },
  datePickerLabel: {
    fontSize: typography.sizes.sm,
    fontWeight: '500',
    color: colors.textPrimary,
    marginBottom: spacing.sm,
    marginTop: spacing.md,
  },
  datePickerButton: {
    height: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.sm,
    paddingHorizontal: spacing.sm,
    justifyContent: 'center',
    backgroundColor: colors.backgroundLight,
  },
  datePickerButtonText: {
    fontSize: typography.sizes.sm,
    color: colors.textPrimary,
  },
  datePickerApply: {
    backgroundColor: colors.primary,
    borderRadius: spacing.md,
    padding: spacing.md,
    alignItems: 'center',
    marginTop: spacing.lg,
  },
  datePickerApplyDisabled: {
    backgroundColor: colors.textSecondary,
  },
  datePickerApplyText: {
    color: colors.white,
    fontSize: typography.sizes.md,
    fontWeight: '600',
  },
  datePickerHelperText: {
    fontSize: typography.sizes.xs,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
  headerRight: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  filterBar: {
    backgroundColor: colors.backgroundLight,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  filterBarContent: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipTextActive: {
    color: colors.white,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  card: {
    backgroundColor: colors.white,
    margin: spacing.md,
    marginBottom: spacing.sm,
    borderRadius: 16,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  projectTitle: {
    fontSize: typography.sizes.lg,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  statItem: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionHeader: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    fontSize: typography.sizes.md,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  expenseListContainer: {
    paddingBottom: spacing.sm,
  },
});
